import type { Locale, Messages, TraceBundle } from '@cryventure/core';
import { tickBundle } from './tickBundle.ts';

/**
 * Test-only: the shape of the isa-x86/isa-armv8 snapshots over the real AES FIPS 197 C.1 bundle
 * (`instructions/fixtures/aesC1.json`, `registers/fixtures/aesC1.json`, generated by running the
 * deriver modules; views may not import derivers, hence the JSON snapshots).
 */
interface IsaSnapshot {
  stepCount: number;
  facets: unknown;
  labels: Record<Locale, Messages>;
}

export interface IsaFixture {
  stepCount: number;
  /** The derived facets of the snapshot, keyed `kind@variant` (JSON imports widen unions, hence `unknown`). */
  derivedFacets: Record<string, unknown>;
  /** A bundle of `facets` (the derived ones by default) whose playhead moves over the AES run's steps. */
  bundle: (facets?: Record<string, unknown>) => TraceBundle;
  /** Deriver labels and AES value names the facets reference. */
  labels: Record<Locale, Messages>;
}

export function isaFixture(snapshot: IsaSnapshot): IsaFixture {
  const derivedFacets = snapshot.facets as Record<string, unknown>;
  return {
    stepCount: snapshot.stepCount,
    derivedFacets,
    bundle: (facets = derivedFacets) => tickBundle('aes', snapshot.stepCount, facets),
    labels: snapshot.labels,
  };
}
