import { RecordingTracer, type Locale, type Messages, type TraceBundle } from '@cryventure/core';
import fixture from './fixtures/aesC1.json';

/**
 * Test-only: the derived facets of the isa-x86 and isa-armv8 derivers over the real AES FIPS 197 C.1
 * bundle, plus the catalog entries they reference (`fixtures/aesC1.json`, generated by running the
 * deriver modules; views may not import derivers, hence the JSON snapshot).
 */
export const AES_STEP_COUNT = fixture.stepCount;

/** The derived facets of the snapshot, keyed `kind@variant` (JSON imports widen unions, hence `unknown`). */
export const aesDerivedFacets = fixture.facets as unknown as Record<string, unknown>;

/** A bundle of `facets` plus an empty-write state facet with the AES run's step count, so the playhead moves. */
export function aesBundle(facets: Record<string, unknown> = aesDerivedFacets): TraceBundle {
  const tracer = new RecordingTracer<'s', { op: 'tick' }>(
    [{ id: 's', labelKey: 'fixture.region.s', elem: 'u8', shape: [1] }],
    { s: [0] },
  );
  for (let i = 0; i < AES_STEP_COUNT; i++)
    tracer.step({ op: 'tick', writes: [], highlights: [], narration: { key: 'fixture.tick' } });
  return {
    schemaVersion: 1,
    producer: { kind: 'primitive', id: 'aes', apiVersion: 1 },
    provenance: 'modeled',
    params: {},
    facets: { 'state@default': tracer.toFacet(), ...facets },
    output: {},
  };
}

/** Deriver labels and AES value names the facets reference. */
export const aesLabels: Record<Locale, Messages> = fixture.labels;
