/**
 * Content Security Policy: the one source (docs/M4.md §9, docs/PLAN.md §7b).
 *
 * The directives live here as data. `scripts/csp-postbuild.ts` hashes every inline `<script>` and
 * `<style>` in `dist/` after `astro build` and uses `buildPolicy` for both delivery paths:
 *  - GitHub Pages: a per-page `<meta http-equiv="Content-Security-Policy">` with that page's hashes;
 *  - Docker/nginx: a real header (union of all hashes) plus the header-only directives
 *    (`frame-ancestors`), written as an nginx include by `renderNginxHeaders`.
 *
 * Build-time only (it uses `node:crypto`); never import it from browser code.
 */
import { createHash } from 'node:crypto';

/** A CSP source expression such as `'self'`, `data:` or `'sha256-…'`. */
export type CspSource = string;
export type CspDirectives = Readonly<Record<string, readonly CspSource[]>>;
export type CspTarget = 'meta' | 'header';

/** Inline content hashes collected from the built HTML; they extend the matching directive. */
export interface InlineHashes {
  readonly scripts: readonly CspSource[];
  readonly styles: readonly CspSource[];
}

/**
 * The policy without inline hashes. Why each non-`'self'` source is here:
 *  - `'wasm-unsafe-eval'`: Pagefind compiles its search index decoder from WebAssembly;
 *  - `style-src-attr 'unsafe-inline'`: Motion, React and Starlight set `style="…"` attributes
 *    (attributes only: `<style>` elements stay hash-locked through `style-src`);
 *  - `img-src data: blob:`: inline SVG/data icons and canvas exports (PenguinLab);
 *  - `worker-src blob:`: module workers created from blob URLs by bundled code.
 */
export const CSP_DIRECTIVES: CspDirectives = {
  'default-src': ["'self'"],
  'script-src': ["'self'", "'wasm-unsafe-eval'"],
  'style-src': ["'self'"],
  'style-src-attr': ["'unsafe-inline'"],
  'img-src': ["'self'", 'data:', 'blob:'],
  'font-src': ["'self'"],
  'connect-src': ["'self'"],
  'worker-src': ["'self'", 'blob:'],
  'manifest-src': ["'self'"],
  'object-src': ["'none'"],
  'base-uri': ["'self'"],
  'form-action': ["'self'"],
};

/** Directives browsers ignore in a `<meta>` CSP; they are sent only as a real header (Docker). */
export const HEADER_ONLY_DIRECTIVES: CspDirectives = {
  'frame-ancestors': ["'none'"],
};

/** Which directive each kind of inline hash extends. */
const HASHED_DIRECTIVE = { scripts: 'script-src', styles: 'style-src' } as const;

/** The other security headers nginx sends with every response (docs/DEPLOY.md). */
export const SECURITY_HEADERS: Readonly<Record<string, string>> = {
  'Referrer-Policy': 'no-referrer',
  'X-Content-Type-Options': 'nosniff',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
  'Cross-Origin-Opener-Policy': 'same-origin',
};

/** `'sha256-<base64>'` of an inline script or style body, exactly as the browser hashes it. */
export function hashSource(content: string): CspSource {
  return `'sha256-${createHash('sha256').update(content, 'utf8').digest('base64')}'`;
}

/** Sorted, de-duplicated hashes, so the policy text is stable for identical builds. */
function uniqueSorted(sources: readonly CspSource[]): CspSource[] {
  return [...new Set(sources)].sort();
}

/** Merges the hashes into their directives (after the base sources) and adds header-only ones. */
export function buildDirectives(hashes: InlineHashes, target: CspTarget): CspDirectives {
  const directives: Record<string, readonly CspSource[]> = { ...CSP_DIRECTIVES };
  for (const kind of ['scripts', 'styles'] as const) {
    const name = HASHED_DIRECTIVE[kind];
    directives[name] = [...(directives[name] ?? []), ...uniqueSorted(hashes[kind])];
  }
  return target === 'header' ? { ...directives, ...HEADER_ONLY_DIRECTIVES } : directives;
}

/** Serialises directives to the policy string: `name src src; name src`. */
export function serializePolicy(directives: CspDirectives): string {
  return Object.entries(directives)
    .map(([name, sources]) => [name, ...sources].join(' '))
    .join('; ');
}

/** The full policy text for one delivery target. */
export function buildPolicy(hashes: InlineHashes, target: CspTarget): string {
  return serializePolicy(buildDirectives(hashes, target));
}

/** The nginx include (`add_header` lines) for the Docker image: CSP header + the other headers. */
export function renderNginxHeaders(policy: string): string {
  const headers = { 'Content-Security-Policy': policy, ...SECURITY_HEADERS };
  const lines = Object.entries(headers).map(([name, value]) => `add_header ${name} "${value}" always;`);
  return [
    '# GENERATED by apps/web/scripts/csp-postbuild.ts from apps/web/src/security/csp.ts. Do not edit.',
    '# Included in every location block (nginx add_header is not inherited once a block defines its own).',
    ...lines,
    '',
  ].join('\n');
}
